package Proyecto::Model::ProtectoDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Proyecto::Schema::ProyectoDB',
    
    connect_info => {
        dsn => 'dbi:SQLite:proyecto.sqlite',
        user => '',
        password => '',
    }
);

=head1 NAME

Proyecto::Model::ProtectoDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Proyecto>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Proyecto::Schema::ProyectoDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

renato

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
